#!/usr/bin/bash

RUBY=/usr/bin/ruby
SCRIPT=/home/fakecrafter/scripts/rofi-translate/leo_search_fr.rb
HISTORY=/home/fakecrafter/scripts/rofi-translate/word_history


# Call menu as long as exit code is 0 (esc is not pressed)
while [ "$?" -eq "0" ]; do
  # write search to history
  [[ ! -z "$input" ]] && `echo $input >> $HISTORY`
  input=`$RUBY $SCRIPT "$input" | rofi -dmenu rofi -theme-str 'window {width: 70%;}' -l 30 -p "Leo Dict: "`
done
