#!/bin/sh
HISTSIZE=100000
SAVEHIST=100000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=900
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/scripts/:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
